### ISSUE TITLE
merge_index breaks on gs:// downloads

### ISSUE THREAD

**Issue by bryanzwu-diffuse** [mosaicml/streaming#559] opened 2024-01-11 20:23 UTC
## Environment
- OS: [Ubuntu 20.04]

## To reproduce

1. Follow this tutorial (https://docs.mosaicml.com/projects/streaming/en/stable/examples/multiprocess_dataset_conversion.html#2.-Group-the-raw-data-and-convert-to-MDS-format-in-parallel)
2. Replace the local out directory out_root with any gcs bucket (gs//:your_bucket/)
3. The code will break with the error message `Failed to download index.json: gs//your_bucket/0/index.json to /tmp/tmpid/0/index.json`

## Expected behavior

It should not error

## Additional context
Looks like the issue is in the join_char being fixed to '//' even though it should be '://'. This is probably a typo. (see https://github.com/mosaicml/streaming/blob/aead15a78f454835c911fae8ab614afad003bdb6/streaming/base/util.py#L404-L420)

**Comment by miguelalba96** [comment] 2024-01-12 12:19
I just got the same exact error:
```
2024-01-12 12:29:04.847 CET
  File "/usr/local/src/kfp/components/./main.py", line 51, in make_records 
2024-01-12 12:29:04.847 CET
    writer.write_data_to_record(data, "test") 
2024-01-12 12:29:04.847 CET
  File "/usr/local/src/kfp/components/writers.py", line 159, in write_data_to_record 
2024-01-12 12:29:04.847 CET
    merge_index(split_path, keep_local=True) 
2024-01-12 12:29:04.847 CET
  File "/usr/local/lib/python3.11/site-packages/streaming/base/util.py", line 252, in merge_index 
2024-01-12 12:29:04.847 CET
    return _merge_index_from_root(*args, **kwargs) 
2024-01-12 12:29:04.847 CET
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
2024-01-12 12:29:04.847 CET
  File "/usr/local/lib/python3.11/site-packages/streaming/base/util.py", line 423, in _merge_index_from_root 
2024-01-12 12:29:04.847 CET
    _merge_index_from_list(remote_index_files, 
2024-01-12 12:29:04.847 CET
  File "/usr/local/lib/python3.11/site-packages/streaming/base/util.py", line 321, in _merge_index_from_list 
2024-01-12 12:29:04.847 CET
    raise RuntimeError(f'Failed to download index.json: {src} to {dest}') from ex 
2024-01-12 12:29:04.848 CET
RuntimeError: Failed to download index.json: gs//bucket-name/fashion-ai/models/20240108-base-clip-336-mds/records/test/chunk_0/index.json to /tmp/tmptgglcihd/gs//bucket-name/fashion-ai/models/20240108-base-clip-336-mds/records/test/chunk_0/index.json`
```
@bryanzwu-diffuse did you fix the typo to `://` and worked?

**Comment by miguelalba96** [comment] 2024-01-12 12:45
I can confirm that fixing the typo `://` solves the issue

**Comment by bryanzwu-diffuse** [comment] 2024-01-12 17:02
Yes--fixing the typo solves the issue, should be a one line change.

**Comment by karan6181** [comment] 2024-01-17 23:54
@miguelalba96 and @bryanzwu-diffuse wondering, why you guys were using prefixes as `gs//` instead of `gs://`. Is that what GCS recommends?

**Comment by bryanzwu-diffuse** [comment] 2024-01-26 21:47
Nope--it's what the mosaic library used when recreating the gcs path that originally included `gs://`--I think it's an issue with parsing and rebuilding the paths.

**Comment by karan6181** [comment] 2024-02-28 15:59
Closing this issue since it is resolved.

**Closed by karan6181** 2024-02-28 15:59 UTC
Labels: bug
