### ISSUE TITLE
StreamingDataset with torch.nn.parallel.DistributedDataParallel

### ISSUE THREAD

**Issue by amallia** [mosaicml/streaming#225] opened 2023-04-14 22:30 UTC
I am trying to use `StreamingDataset` with `torch.nn.parallel.DistributedDataParallel` by:
```
nranks = 'WORLD_SIZE' in os.environ and int(os.environ['WORLD_SIZE'])
nranks = max(1, nranks)
args.batch_size = args.batch_size // nranks


local = "/tmp/mds_triples_v1/"
dataset = StreamingDataset(local=local, remote=args.s3_train_path, shuffle=True)

    
train_dataloader = DataLoader(
             dataset,
             batch_size=args.batch_size,
             collate_fn=collate_fn,
             num_workers=10,
 )

.... 

model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.rank],
                                                      output_device=args.rank,
                                                      find_unused_parameters=True)
```

I am wondering if in this way my GPUs will all see the same data. I used to use `torch.utils.data.distributed.DistributedSampler` to avoid that in the past, but I am not sure if I can integrate it with `StreamingDataset`

**Comment by karan6181** [comment] 2023-04-16 20:24
Hi @amallia, thanks for filing an issue. 

- `StreamingDataset` is an Iterable style Dataset ([torch.utils.data.IterableDataset](https://pytorch.org/docs/stable/data.html#torch.utils.data.IterableDataset)) instead of Map style Dataset ([torch.utils.data.Dataset](https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset)). Hence, it does not require any type of Sampler. `StreamingDataset` will distribute the samples across GPUs/Nodes for you.
- If you have set the `WORLD_SIZE`, `LOCAL_WORLD_SIZE`, and `RANK` correctly, then `StreamingDataset` will splits the dataset across GPUs/Nodes without any sample duplication.
  - Also, you don't need to worry about the above environment variables if you use [torchrun](https://pytorch.org/docs/stable/elastic/run.html?highlight=torchrun) command which sets those environment variables for you and `StreamingDataset` just fetches those environment variables.

**Comment by amallia** [comment] 2023-04-16 20:48
Thanks @karan6181 for the explaination.

If I understand correctly, in case I have a dataset of 8M samples and my training code running on 8 GPUs using the [torchrun](https://pytorch.org/docs/stable/elastic/run.html?highlight=torchrun) command, those GPUs will see 1M non-overlapping samples automatically.

Is this documented anywhere? Is there an easy way to ensure/test that the program is doing the right thing?

Thanks!

**Comment by karan6181** [comment] 2023-04-16 21:44
> If I understand correctly, in case I have a dataset of 8M samples and my training code running on 8 GPUs using the [torchrun](https://pytorch.org/docs/stable/elastic/run.html?highlight=torchrun) command, those GPUs will see 1M non-overlapping samples automatically.

Yes

> Is this documented anywhere? Is there an easy way to ensure/test that the program is doing the right thing?

If you have a sample_id or any sequential id in your dataset, then one way to validate is to iterate the dataloader and print the sample_id or id with the rank as a prefix or try printing the samples on a small dataset to being with to see if all the ranks sees the different samples or not.

**Comment by amallia** [comment] 2023-04-16 21:47
I think your products, this one included, are quite solid, but I would make documentation a bit more clear. For example, I couldn't find the above information anywhere. Am I missing something?

**Comment by karan6181** [comment] 2023-04-16 23:06
Thanks for your suggestion. We have a plan to improve our documentation and we will add your feedback and make it more explicit. We have some of such information scattered at different place such as checkout `Correctness: No Silent Pitfalls` section mentioned in this [blog](https://www.mosaicml.com/blog/mosaicml-streamingdataset) and `no-divisibility` section [here](https://github.com/mosaicml/streaming#no-divisibility-requirements).

**Comment by karan6181** [comment] 2023-12-19 16:39
We are closing this issue since the issue is resolved. We plan to improve our documentation and will include your suggestions. Thank You!

**Closed by karan6181** 2023-12-19 16:39 UTC
Labels: enhancement
