### ISSUE TITLE
Error writing to databricks UC volume

### ISSUE THREAD

**Issue by JK87iab** [mosaicml/streaming#703] opened 2024-06-15 21:15 UTC
## Environment
Databricks Runtime 14.3 LTS ML
databricks-automl-runtime==0.2.20
databricks-cli==0.18.0
databricks-feature-engineering==0.2.1
databricks-sdk==0.28.0
mosaicml-streaming==0.7.6

## To reproduce
```

import numpy as np
from PIL import Image
from shutil import rmtree
from uuid import uuid4
from streaming import MDSWriter

# Local or remote directory path to store the output compressed files.
out_root = "dbfs:/Volumes/**name.schema/volume_name**/test"
#out_root = '/dbfs/FileStore/test'
os.environ['DATABRICKS_HOST'] = 'https://**address**.azuredatabricks.net'
os.environ['DATABRICKS_TOKEN'] = dbutils.secrets.get(..... )
# A dictionary of input fields to an Encoder/Decoder type
columns = {
    'uuid': 'str',
    'img': 'jpeg',
    'clf': 'int'
}

# Compression algorithm name
compression = 'zstd'

# Generate random images and classes
samples = [
    {
        'uuid': str(uuid4()),
        'img': Image.fromarray(np.random.randint(0, 256, (32, 48, 3), np.uint8)),
        'clf': np.random.randint(10),
    }
    for _ in range(1000)
]

# Use `MDSWriter` to iterate through the input data and write to a collection of `.mds` files.
with MDSWriter(out=out_root, columns=columns, compression=compression) as out:
    for sample in samples:
        out.write(sample)
```

Error trace:
```

exception calling callback for <Future at 0x7faba572cbb0 state=finished raised InvalidParameterValue>
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 342, in _invoke_callbacks
    callback(self)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/streaming/base/format/base/writer.py", line 330, in exception_callback
    raise exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/streaming/base/storage/upload.py", line 877, in upload_file
    _upload_file()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/streaming/base/util.py", line 525, in new_func
    raise e
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/streaming/base/util.py", line 521, in new_func
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/streaming/base/storage/upload.py", line 875, in _upload_file
    self.client.files.upload(remote_filename_wo_prefix, f)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/service/files.py", line 968, in upload
    self._api.do('PUT',
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 131, in do
    response = retryable(self._perform)(method,
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 242, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.platform.InvalidParameterValue: GetVolume full_name_arg is not a valid name
exception calling callback for <Future at 0x7faba5783d90 state=finished raised InvalidParameterValue>
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 342, in _invoke_callbacks
    callback(self)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/streaming/base/format/base/writer.py", line 330, in exception_callback
    raise exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/streaming/base/storage/upload.py", line 877, in upload_file
    _upload_file()
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/streaming/base/util.py", line 525, in new_func
    raise e
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/streaming/base/util.py", line 521, in new_func
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/streaming/base/storage/upload.py", line 875, in _upload_file
    self.client.files.upload(remote_filename_wo_prefix, f)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/service/files.py", line 968, in upload
    self._api.do('PUT',
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 131, in do
    response = retryable(self._perform)(method,
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 54, in wrapper
    raise err
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/retries.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/databricks/sdk/core.py", line 242, in _perform
    raise self._make_nicer_error(response=response, **payload) from None
databricks.sdk.errors.platform.InvalidParameterValue: GetVolume full_name_arg is not a valid name
```

Writing to dbfs works fine.

**Comment by snarayan21** [comment] 2024-06-17 20:40
Thanks for raising this @JK87iab! @XiaohanZhangCMU could you take a look?

**Comment by XiaohanZhangCMU** [comment] 2024-06-18 06:54
Thank you @JK87iab !

I tried to reproduce the error on a single-assigned cluster with 14.3 LTS ML using the script you posted above. But it turns out working fine, without any error message. 

I wonder if it is something related to your dbutils credentials, are you able to run a file-uploading script like below?

```
from streaming.base.storage import CloudUploader
cu = CloudUploader.get( out=("/tmp/", "dbfs:/Volumes/main/mosaic_hackathon/managed-volume/test_issue703"), exist_ok=True)
!echo "Some text here." > /tmp/myfile.txt
cu.upload_file("myfile.txt")
```

**Comment by XiaohanZhangCMU** [comment] 2024-06-18 06:56
This is the content of my notebook: 

```
%pip install databricks-automl-runtime==0.2.20
%pip install databricks-cli==0.18.0
%pip install databricks-feature-engineering==0.2.1
%pip install databricks-sdk==0.28.0
%pip install mosaicml-streaming==0.7.6
dbutils.library.restartPython()

import numpy as np
from PIL import Image
from shutil import rmtree
from uuid import uuid4
from streaming import MDSWriter

# Local or remote directory path to store the output compressed files.
out_root = "dbfs:/Volumes/main/mosaic_hackathon/managed-volume/test_issue703"
#out_root = '/dbfs/FileStore/test'
# os.environ['DATABRICKS_HOST'] = 'https://**address**.azuredatabricks.net'
# os.environ['DATABRICKS_TOKEN'] = dbutils.secrets.get(..... )
# A dictionary of input fields to an Encoder/Decoder type
columns = {
    'uuid': 'str',
    'img': 'jpeg',
    'clf': 'int'
}

# Compression algorithm name
compression = 'zstd'

# Generate random images and classes
samples = [
    {
        'uuid': str(uuid4()),
        'img': Image.fromarray(np.random.randint(0, 256, (32, 48, 3), np.uint8)),
        'clf': np.random.randint(10),
    }
    for _ in range(1000)
]

# Use `MDSWriter` to iterate through the input data and write to a collection of `.mds` files.
with MDSWriter(out=out_root, columns=columns, compression=compression) as out:
    for sample in samples:
        out.write(sample)
```

**Comment by JK87iab** [comment] 2024-06-20 15:17
Hey thx for the quick response. Works on my end now too.

I think I was the bug. Used a dot (.) instead of / to write the path to the volume in UC.

thx

**Comment by snarayan21** [comment] 2024-06-20 16:58
Thanks! closing this issue.

**Closed by snarayan21** 2024-06-20 16:58 UTC
Labels: bug
